name: CI Pipeline
on: [push, pull_request]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install packages
        run: yarn install
      - name: Build 
        run: yarn build
      - name: Tests
        run: yarn test:prod
      - name: publish Coverage
        timeout-minutes: 1
        continue-on-error: true
        run: bash <(curl -s https://codecov.io/bash) -B ${{ github.ref }} -f coverage/coverage-final.json